import os

# List of SVG filenames in the order they appear in the folder
svg_filenames = [
    "img 1.svg",
    "img 2.svg",
    "img 3.svg",
    "img 4.svg",
    "img 5.svg",
    "img 6.svg",
    "img 7.svg",
    "img 8.svg",
    "img 9.svg",
    "img 10.svg",
    "img 11.svg",
    "img 12.svg",
    "img 13.svg",
    "img 14.svg",
    "img 15.svg",
    "img 16.svg",
    "img 17.svg",
    "img 18.svg",
    "img 19.svg",
    "img 20.svg",
    "img 21.svg",
    "img 22.svg",
    "img 23.svg",
    "img 24.svg",
    "img 25.svg",
    "img 26.svg",
    "img 27.svg",
    "img 28.svg",
    "img 29.svg",
    "img 30.svg",
    "img 31.svg",
    "img 32.svg",
    "img 33.svg",
    "img 34.svg",
    "img 35.svg",
    "img 36.svg",
    "img 37.svg",
    "img 38.svg",
    "img 39.svg",
    "img 40.svg",
    "img 41.svg",
    "img 42.svg",
    "img 43.svg",
    "img 44.svg",
    "img 45.svg",
    "img 46.svg",
    "img 47.svg",
    "img 48.svg",
    "img 49.svg",
    "img 50.svg",
    "img 51.svg",
    "img 52.svg",
    "img 53.svg",
    "img 54.svg",
    "img 55.svg",
    "img 56.svg",
    "img 57.svg",
    "img 58.svg",
    "img 59.svg",
    "img 60.svg",
    "img 61.svg"
]

# List of new filenames corresponding to the SVG filenames
new_filenames = [
    "stock-image-generator",
    "avatar",
    "interior",
    "remove-background",
    "swap-face",
    "dalle3",
    "age-transform",
    "photo-restore",
    "ad-inpaint",
    "qr-generator",
    "sketch-to-image",
    "image-manipulator",
    "article-generator",
    "blog-title-generator",
    "content-rephrase",
    "story-generator",
    "slide-generator",
    "content-summary",
    "grammar-correction",
    "content-translator",
    "email-writer",
    "chat-with-pdf",
    "chat-with-characters",
    "create-character-bot",
    "chat-with-place",
    "chat-with-book",
    "chat-with-movie",
    "cover-letter-generator",
    "quiz-generator",
    "flashcard-generator",
    "image-analysis",
    "motivational-coach",
    "chat-with-youtube",
    "chat-with-internet",
    "youtube-script",
    "instagram-caption",
    "tweet-generator",
    "linkedin-post-generator",
    "facebook-post-generator",
    "instagram-reel",
    "tiktok-script",
    "job-posting",
    "chat-about-place",
    "itinerary",
    "history",
    "interesting-facts",
    "meal-planner",
    "food-info",
    "recipe-gpt",
    "nutrients-tracker",
    "chat-about-book",
    "book",
    "non-disclosure-agreement",
    "contract-agreement",
    "will-agreement",
    "rental-agreement",
    "terminology-explainer",
    "terms-conditions-page",
    "privacy-page",
    "audio-note"
]

# Path to the directory containing the SVG files
directory_path = "/home/ishan/Downloads/beeyond"  # Change this to your actual directory

# Change working directory to the directory containing the SVG files
os.chdir(directory_path)

# Loop over the SVG files and rename them
for svg_file, new_name in zip(svg_filenames, new_filenames):
    old_path = os.path.join(directory_path, svg_file)
    new_path = os.path.join(directory_path, f"{new_name}.svg")
    if os.path.exists(old_path):
        os.rename(old_path, new_path)
        print(f"Renamed: {svg_file} to {new_name}.svg")
    else:
        print(f"File not found: {svg_file}")
